export type { SecretCodec } from '../secrets/codec.js'
export { createSecretCodec, decodeEncryptionKey, SecretCodecError } from '../secrets/codec.js'
export type {
  AiConfig,
  AiConfigData,
  RedactedAiStatus,
  SetAiProviderKeyOptions,
  UpsertAiConfigOptions,
} from './ai-config.js'
export {
  AI_CONNECTOR_PROVIDER,
  aiConfigDataSchema,
  getAiConfig,
  getAiProviderKey,
  getRedactedAiStatus,
  listConfiguredAiProviders,
  setAiProviderKey,
  upsertAiConfig,
} from './ai-config.js'
export type {
  AttachmentReaderQuery,
  AttachmentRow,
  AttachTarget,
  CreateAttachmentInput,
  OrphanedAttachmentsOptions,
  TargetScopeQuery,
  UploadScopeQuery,
} from './attachment.js'
export {
  attachAttachment,
  canUploadToTeam,
  createAttachment,
  deleteAttachment,
  findAttachmentForReader,
  listOrphanedAttachments,
  targetsAreInTeam,
} from './attachment.js'
export type { Database, DatabaseOptions } from './client.js'
export { createDatabase, pingDatabase } from './client.js'
export type {
  RecordConnectorSyncOptions,
  RedactedConnectorStatus,
  RedactedInstallation,
  SetConnectorSecretOptions,
  SetRepoTeamOptions,
  UpsertConnectorConfigOptions,
  UpsertConnectorInstallationOptions,
} from './connector.js'
export {
  ConnectorAuthorizationError,
  deleteConnectorInstallation,
  deleteConnectorSecret,
  findConnectorConfigByProvider,
  findConnectorInstallation,
  getConnectorConfig,
  getConnectorConfigById,
  getConnectorInstallation,
  getConnectorSecret,
  getInstallationEtag,
  getRedactedConnectorStatus,
  listConnectorConfigs,
  listConnectorConfigsByProvider,
  listConnectorInstallations,
  listConnectorSecretKeys,
  recordConnectorSync,
  removeInstallationRepoTeam,
  resolveTeamForRepo,
  setConnectorSecret,
  setInstallationEtag,
  setInstallationRepoTeam,
  upsertConnectorConfig,
  upsertConnectorInstallation,
} from './connector.js'
export type { CycleNeedingDigest, CyclesNeedingDigestOptions } from './cycle-digest.js'
export {
  cyclesNeedingDigest,
  getCycleDigestByCycle,
  getWorkspaceAiSpendUsd,
} from './cycle-digest.js'
export { cycleFactsForTeam } from './cycle-facts.js'
export type {
  AcceptInviteOptions,
  AcceptInviteRefusal,
  AcceptInviteResult,
  InviteEmailTarget,
} from './invite.js'
export { acceptInvite, inviteEmailTarget } from './invite.js'
export type {
  AutoSubscribeRow,
  DeleteSubscriptionsForTeamMemberOptions,
} from './issue-subscription.js'
export {
  autoSubscribeMentioned,
  deleteSubscriptionsForMember,
  deleteSubscriptionsForTeamMember,
  subscribersOfIssue,
} from './issue-subscription.js'
export { lookupWorkspaceRole } from './membership.js'
export type { MigrationOutcome } from './migrate.js'
export { createMigrator, migrateToLatest } from './migrate.js'
export type {
  DeleteNotificationsForTeamMemberOptions,
  MarkAllNotificationsReadOptions,
  NotificationEvent,
  NotificationKey,
  PendingNotificationEmail,
  PendingNotificationEmailsOptions,
} from './notification.js'
export {
  deleteNotificationsForMember,
  deleteNotificationsForTeamMember,
  deleteNotificationsOlderThan,
  markAllNotificationsRead,
  pendingNotificationEmails,
  recordNotifications,
  stampNotificationsEmailed,
} from './notification.js'
export type { ReplicationSlot, ReplicationStatus } from './replication.js'
export {
  assertReplicationHealthy,
  describeReplicationStatus,
  readReplicationStatus,
} from './replication.js'
export type {
  EnsureSearchIndexResult,
  EnsureSearchIndexStatus,
  ReconcileDiffOptions,
  SearchDocumentKey,
  SearchDocumentRow,
  SearchDocumentsOptions,
  SearchEntityType,
  SearchHit,
  SearchIndexFreshness,
  SearchScope,
  SearchSourceRow,
  StaleBatchOptions,
} from './search.js'
export {
  DEFAULT_TEXT_SEARCH_CONFIG,
  deleteSearchDocuments,
  ensureSearchIndex,
  intersectScope,
  orphanedCommentDocuments,
  reconcileDiffBatch,
  resolveSearchScope,
  SEARCH_ENTITY_TYPES,
  SEARCH_FTS_INDEX_NAME,
  SEARCH_WRITE_CHUNK,
  SearchTextConfigError,
  searchDocuments,
  searchIndexDefinitionSql,
  searchIndexFreshness,
  searchWatermark,
  staleCommentBatch,
  staleIssueBatch,
  upsertSearchDocuments,
} from './search.js'
export type {
  BootstrapFirstAdminOptions,
  SeedDemoContentOptions,
  SeedDemoContentResult,
  SeedWorkspaceOptions,
} from './seed.js'
export {
  BOOTSTRAP_LOCK_ID,
  bootstrapFirstAdmin,
  DEFAULT_WORKSPACE_NAME,
  DEMO_CONTENT_LOCK_ID,
  SEED_LOCK_ID,
  seedDemoContent,
  seedWorkspace,
} from './seed.js'
export type {
  Attachment,
  AttachmentTable,
  AttachmentUpdate,
  CiCheck,
  CiCheckTable,
  CiCheckUpdate,
  Comment,
  CommentTable,
  CommentUpdate,
  ConnectorConfig,
  ConnectorConfigTable,
  ConnectorConfigUpdate,
  ConnectorInstallation,
  ConnectorInstallationTable,
  ConnectorInstallationUpdate,
  ConnectorSecret,
  ConnectorSecretTable,
  ConnectorSecretUpdate,
  Cycle,
  CycleDigest,
  CycleDigestTable,
  CycleDigestUpdate,
  CycleSequence,
  CycleSequenceTable,
  CycleTable,
  CycleUpdate,
  DB,
  Deployment,
  DeploymentTable,
  DeploymentUpdate,
  Invite,
  InviteTable,
  InviteUpdate,
  Issue,
  IssueLabel,
  IssueLabelTable,
  IssueLink,
  IssueLinkTable,
  IssueSequence,
  IssueSequenceTable,
  IssueSubscription,
  IssueSubscriptionTable,
  IssueSubscriptionUpdate,
  IssueTable,
  IssueUpdate,
  Label,
  LabelTable,
  LabelUpdate,
  NewAttachment,
  NewCiCheck,
  NewComment,
  NewConnectorConfig,
  NewConnectorInstallation,
  NewConnectorSecret,
  NewCycle,
  NewCycleDigest,
  NewDeployment,
  NewInvite,
  NewIssue,
  NewIssueLabel,
  NewIssueLink,
  NewIssueSubscription,
  NewLabel,
  NewNotification,
  NewPullRequest,
  NewReview,
  NewSavedView,
  NewSearchDocument,
  NewTeam,
  NewTeamMembership,
  NewWorkspace,
  NewWorkspaceMember,
  Notification,
  NotificationTable,
  NotificationUpdate,
  PullRequest,
  PullRequestTable,
  PullRequestUpdate,
  Review,
  ReviewTable,
  ReviewUpdate,
  SavedView,
  SavedViewTable,
  SavedViewUpdate,
  SearchDocument,
  SearchDocumentTable,
  SearchDocumentUpdate,
  Team,
  TeamMembership,
  TeamMembershipTable,
  TeamTable,
  TeamUpdate,
  Timestamp,
  TimestampOrNull,
  User,
  UserTable,
  Workspace,
  WorkspaceMember,
  WorkspaceMemberTable,
  WorkspaceMemberUpdate,
  WorkspaceTable,
  WorkspaceUpdate,
} from './types.js'
